pipeline {
  agent any
  stages {
    stage('Nix Build') {
      steps {
        sh '''. ~/.nix-profile/etc/profile.d/nix.sh

nix-shell --run exit | tee ./nix-build.log'''
      }
    }

    stage('Build') {
      steps {
        sh '''. ~/.nix-profile/etc/profile.d/nix.sh


nix-shell --command "make all"'''
      }
    }

    stage('Run tests') {
      steps {
        sh '''. ~/.nix-profile/etc/profile.d/nix.sh

nix-shell --command "make test"'''
      }
    }

  }
  post {
    success {
      discordSend description: "Build Completed", link: env.BUILD_URL, result: currentBuild.currentResult, title: JOB_NAME, webhookURL: "${env.DISCORD_ENDPOINT}"
    }

    unstable {
      discordSend description: "Build Completed (Unstable)", link: env.BUILD_URL, result: currentBuild.currentResult, title: JOB_NAME, webhookURL: "${env.DISCORD_ENDPOINT}"
    }

    failure {
      discordSend description: "Build Failed", link: env.BUILD_URL, result: currentBuild.currentResult, title: JOB_NAME, webhookURL: "${env.DISCORD_ENDPOINT}"
    }
  }
}
